# Generated by Django 5.0.3 on 2024-05-27 23:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('semester', models.CharField(choices=[('1', 'Primer'), ('2', 'Segundo')], max_length=10)),
                ('is_extension', models.BooleanField()),
                ('comment', models.TextField(null=True)),
                ('state_documents', models.SmallIntegerField(choices=[(0, 'Documentos no revisados'), (1, 'Modificación de los documentos solicitada'), (2, 'Documentos aprobados')], default=0)),
                ('modified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(null=True)),
                ('training_session', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), null=True, size=None)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.call')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
