# Generated by Django 5.0.3 on 2024-04-24 11:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalapplication',
            name='application',
        ),
        migrations.RemoveField(
            model_name='application',
            name='data_processing_form',
        ),
        migrations.RemoveField(
            model_name='application',
            name='doc_id_student',
        ),
        migrations.RemoveField(
            model_name='application',
            name='grades_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='request_form',
        ),
        migrations.RemoveField(
            model_name='application',
            name='responsibility_form',
        ),
        migrations.AlterField(
            model_name='application',
            name='semester',
            field=models.CharField(choices=[('1', 'Primer'), ('2', 'Segundo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='training_session',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='InternationalApplication',
        ),
        migrations.DeleteModel(
            name='NationalApplication',
        ),
    ]
