# Generated by Django 5.0.3 on 2024-05-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
