# Generated by Django 5.0.3 on 2024-05-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='comment_approved',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='comment_docs',
        ),
    ]
