# Generated by Django 5.0.3 on 2024-04-15 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='application',
            name='info_courses',
        ),
        migrations.RemoveField(
            model_name='application',
            name='medication',
        ),
        migrations.AlterField(
            model_name='application',
            name='approve_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_documents',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='InternationalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_letter', models.CharField(max_length=50)),
                ('language_doc', models.CharField(max_length=50)),
                ('economic_letter', models.CharField(max_length=50)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='NationalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigueme_doc', models.CharField(max_length=50)),
                ('payment_tuition', models.CharField(max_length=50)),
                ('eps_certificate', models.CharField(max_length=50)),
                ('economic_letter', models.CharField(max_length=50)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
    ]
