# Generated by Django 5.0.3 on 2024-04-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
