# Generated by Django 5.0.3 on 2024-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_comment_approved_application_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.TextField(default=False),
        ),
    ]
