# Generated by Django 5.0.3 on 2024-05-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approve_documents',
        ),
        migrations.AddField(
            model_name='application',
            name='state_documents',
            field=models.SmallIntegerField(choices=[(0, 'Documentos no revisados'), (1, 'Modificación de los documentos solicitada'), (2, 'Documentos aprobados')], default=0),
        ),
    ]
