# Generated by Django 5.0.3 on 2024-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
