-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Student" DROP CONSTRAINT IF EXISTS "ID";

ALTER TABLE IF EXISTS public."Employee" DROP CONSTRAINT IF EXISTS "ID";



DROP TABLE IF EXISTS public."Person";

CREATE TABLE IF NOT EXISTS public."Person"
(
    "ID" integer NOT NULL,
    name character varying NOT NULL,
    lastname character varying NOT NULL,
    birth date NOT NULL,
    sex character varying NOT NULL,
    country character varying NOT NULL,
    city character varying NOT NULL,
    phone bigint NOT NULL,
    email character varying NOT NULL,
    address character varying NOT NULL,
    age smallint NOT NULL,
    ethnicity character varying NOT NULL DEFAULT "None",
    headquarter character varying NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS public."Student";

CREATE TABLE IF NOT EXISTS public."Student"
(
    "ID" integer NOT NULL,
    average smallint NOT NULL,
    "PBM" smallint NOT NULL,
    advance smallint NOT NULL,
    "Faculty" character varying NOT NULL,
    major character varying NOT NULL,
    headquarters character varying NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS public."Employee";

CREATE TABLE IF NOT EXISTS public."Employee"
(
    "ID" smallint NOT NULL,
    dependence character varying NOT NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public."Student"
    ADD CONSTRAINT "ID" FOREIGN KEY ("ID")
    REFERENCES public."Person" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_ID"
    ON public."Student"("ID");


ALTER TABLE IF EXISTS public."Employee"
    ADD CONSTRAINT "ID" FOREIGN KEY ("ID")
    REFERENCES public."Person" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_ID"
    ON public."Employee"("ID");

END;