# Generated by Django 5.0.3 on 2024-04-03 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(max_length=50)),
                ('cellphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[('E', 'Estudiante'), ('T', 'Trabajador')], max_length=2)),
                ('type_document', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjera'), ('PA', 'Pasaporte')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1)),
                ('birth_place', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(choices=[('I', 'Indígena'), ('A', 'Afrocolombiana'), ('RG', 'Rom o gitana'), ('N', 'Ninguna')], default='N', max_length=2)),
                ('headquarter', models.CharField(choices=[('A', 'Amazonia'), ('C', 'Caribe'), ('B', 'Bogotá'), ('MA', 'Manizales'), ('ME', 'Medellin'), ('O', 'Orinoquía'), ('P', 'Palmira'), ('T', 'Tumaco'), ('LP', 'La Paz')], default='B', max_length=2)),
                ('PAPA', models.FloatField()),
                ('PAPI', models.FloatField()),
                ('PA', models.FloatField()),
                ('PBM', models.SmallIntegerField()),
                ('advance', models.FloatField()),
                ('faculty', models.CharField(choices=[('AGRARIAS', 'Ciencias Agrarias')], max_length=10)),
                ('major', models.CharField(choices=[('ISC', 'Ingeniería de Sistemas y Computación')], max_length=5)),
                ('is_enrolled', models.BooleanField()),
                ('date_banned_mobility', models.DateField(default='2000-01-01')),
                ('is_banned_behave_un', models.BooleanField()),
                ('admission', models.CharField(choices=[('REG', 'Regular')], default='REG', max_length=3)),
                ('study_level', models.CharField(choices=[('PRE', 'Pregrado')], max_length=3)),
                ('num_semesters', models.SmallIntegerField()),
                ('calls_done', models.ManyToManyField(to='call.call')),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.contactperson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
