# Generated by Django 5.0.3 on 2024-04-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_banned_mobility',
        ),
    ]
