# Generated by Django 5.0.3 on 2024-04-10 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_date_banned_mobility'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_banned_mobility',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
