# Generated by Django 5.0.3 on 2024-04-06 15:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('webpage', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('NA', 'Norte América'), ('CA', 'Centro América'), ('SA', 'Sur América'), ('EU', 'Europa'), ('AS', 'Asia'), ('AF', 'África'), ('OC', 'Oceanía'), ('AN', 'Antártida')])),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'Inglés'), ('es', 'Español'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('zh', 'Chino'), ('ja', 'Japonés'), ('ko', 'Coreano'), ('ar', 'Árabe'), ('ru', 'Ruso'), ('hi', 'Hindi')], max_length=2), size=None)),
                ('academic_offer', models.CharField(max_length=255)),
                ('exchange_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('begin_date', models.DateField()),
                ('deadline', models.DateField()),
                ('min_advance', models.FloatField()),
                ('min_papa', models.FloatField()),
                ('format', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1)),
                ('study_level', models.CharField(choices=[('PRE', 'Pregrado'), ('POS', 'Posgrado'), ('DOC', 'Doctorado')], max_length=10)),
                ('year', models.SmallIntegerField()),
                ('semester', models.CharField(choices=[(1, 'First'), (2, 'Second')], max_length=10)),
                ('description', models.TextField()),
                ('available_slots', models.SmallIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('highest_papa_winner', models.FloatField(default=0.0)),
                ('minimum_papa_winner', models.FloatField(default=0.0)),
                ('selected', models.IntegerField(default=0)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.university')),
            ],
        ),
    ]
