# Generated by Django 5.0.3 on 2024-04-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='language',
            field=models.CharField(choices=[('en', 'Inglés'), ('es', 'Español'), ('fr', 'Francés'), ('pt', 'Portugués'), ('de', 'Alemán'), ('it', 'Italiano'), ('ko', 'Coreano'), ('ru', 'Ruso'), ('zh', 'Chino'), ('xx', 'Otro')], max_length=5),
        ),
    ]
