# Generated by Django 5.0.3 on 2024-04-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(choices=[('NA', 'Norte América'), ('LA', 'Latinoamérica'), ('EU', 'Europa'), ('OC', 'Oceanía'), ('AS', 'Oceanía'), ('AN', 'Uniandes'), ('SG', 'Convenio Sigueme/Nacional')], max_length=10),
        ),
    ]
