# Generated by Django 5.0.3 on 2024-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_alter_call_semester_alter_call_study_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='format',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1),
        ),
    ]
