# Generated by Django 5.0.3 on 2024-03-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_alter_call_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='semester',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second')], max_length=10),
        ),
    ]
