# Generated by Django 5.0.3 on 2024-04-02 23:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_alter_university_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'Inglés'), ('es', 'Español'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('zh', 'Chino'), ('ja', 'Japonés'), ('ko', 'Coreano'), ('ar', 'Árabe'), ('ru', 'Ruso'), ('hi', 'Hindi')], max_length=3), size=None),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
