# Generated by Django 5.0.3 on 2024-04-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_alter_university_language_alter_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(choices=[('NA', 'Norte América'), ('CA', 'Centro América'), ('SA', 'Sur América'), ('EU', 'Europa'), ('AS', 'Asia'), ('AF', 'África'), ('OC', 'Oceanía'), ('AN', 'Antártida')]),
        ),
    ]
