# Generated by Django 5.0.3 on 2024-04-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0007_alter_university_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='highest_PAPA_winner',
            field=models.SmallIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='call',
            name='minium_PAPA_winner',
            field=models.SmallIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='call',
            name='selected',
            field=models.SmallIntegerField(default=0),
        ),
    ]
