# Generated by Django 5.0.3 on 2024-04-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0009_rename_highest_papa_winner_call_highest_papa_winner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='minium_papa_winner',
            new_name='minimum_papa_winner',
        ),
    ]
