# Generated by Django 5.0.3 on 2024-04-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0010_rename_minium_papa_winner_call_minimum_papa_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='highest_papa_winner',
        ),
        migrations.RemoveField(
            model_name='call',
            name='minimum_papa_winner',
        ),
        migrations.AddField(
            model_name='call',
            name='minium_PAPA_winner',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='call',
            name='selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='call',
            name='highest_PAPA_winner',
            field=models.FloatField(default=0.0),
        ),
    ]
